name: Install, Build & Run Cypress

on: [push, pull_request]
env:
  CHILD_CONCURRENCY: 1
  NODE_ENV: test
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  CYPRESS_TEST_USERNAME: ${{ secrets.CYPRESS_TEST_USERNAME }}
  CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_CACHE_FOLDER: ${{ secrets.CYPRESS_CACHE_FOLDER }}
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.15.1]
    steps:
      - name: Extract Branch Name
        run: |
          echo "::set-env name=BRANCH::${GITHUB_REF#refs/heads/}"
          echo ${GITHUB_REF#refs/heads/}
          echo ${GITHUB_REF}
        # if: github.event_name == 'pull_request'
      # - name: Extract Branch Name (Push)
      #   run: |
      #     echo "::set-env name=BRANCH::${GITHUB_REF##*/}"
      #     echo ${GITHUB_REF##*/}
      #   if: github.event_name == 'push'
      - uses: actions/checkout@v2.3.2
        with:
          ref: ${{ env.BRANCH }}
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory
        id: yarn-cache-directory
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Load Cached Yarn Modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-directory.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Load Cached Cypress
        uses: actions/cache@v1
        with:
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cypress-
      - name: Install Packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn;
      - name: Run Unit Tests
        run: yarn test:unit;
      - name: Run Coverage Tests
        run: yarn test;
      - name: Create Badge For Coverage Results
        if: github.event_name == 'push'
        run: yarn create-coverage-badge;
      - name: Commit Coverage Results
        if: github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./coverage/shields.json -f
          git checkout .
          git diff-index --quiet HEAD || git commit -m "Add Coverage Results"
      - name: Push changes
        if: github.event_name == 'push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          branch: ${{ env.BRANCH }}
  auto_merge:
    needs: [test]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
    steps:
      - name: "@dependabot merge"
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.ACTIONS_TOKEN}}
          script: |
            github.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body: '@dependabot merge'
            })
